[tool.poetry]
name = "twisted-slice"
version = "0.1.0"
description = "the game"
authors = ["tima-kuchin <kuchin.timur@bk.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pygame = "^2.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
